#!/bin/sh

set -eu

BUILD_SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
SOURCE_DIR="$BUILD_SCRIPT_DIR/gml-manager-src"
TARGET_FILE="$BUILD_SCRIPT_DIR/gml-manager.sh"
MODULES='00-config.sh
10-i18n.sh
20-cli.sh
30-network.sh
40-system.sh
50-files.sh
60-compose.sh
70-commands.sh
99-main.sh'

usage() {
    echo "Usage: $0 [--check]"
}

render_manager() {
    render_target="$1"

    {
        printf '%s\n' '#!/bin/sh'
        printf '%s\n\n' '# Generated by installer/build-gml-manager.sh. Do not edit directly.'

        first_module=1
        for module_name in $MODULES; do
            if [ "$first_module" -eq 0 ]; then
                printf '\n'
            fi
            sed '$ { /^$/d; }' "$SOURCE_DIR/$module_name"
            first_module=0
        done
    } > "$render_target"
}

check_sources() {
    for module_name in $MODULES; do
        if [ ! -f "$SOURCE_DIR/$module_name" ]; then
            echo "Missing GML Manager module: $SOURCE_DIR/$module_name" >&2
            return 1
        fi
    done
}

validate_source_syntax() {
    for module_name in $MODULES; do
        if ! sh -n "$SOURCE_DIR/$module_name"; then
            echo "Invalid shell syntax in GML Manager module: $SOURCE_DIR/$module_name" >&2
            return 1
        fi
    done
}

mode=build
case "${1:-}" in
    "") ;;
    --check) mode=check ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac

if [ "$#" -gt 1 ]; then
    usage >&2
    exit 2
fi

check_sources
validate_source_syntax

temporary_file=$(mktemp "$BUILD_SCRIPT_DIR/.gml-manager.sh.XXXXXX")
cleanup_temporary_file() {
    rm -f "$temporary_file"
}
trap cleanup_temporary_file 0
trap 'exit 1' 1 2 15
render_manager "$temporary_file"
if ! sh -n "$temporary_file"; then
    echo "Invalid shell syntax in generated installer/gml-manager.sh" >&2
    exit 1
fi
chmod 0755 "$temporary_file"

if [ "$mode" = check ]; then
    if [ ! -x "$TARGET_FILE" ] || ! cmp -s "$temporary_file" "$TARGET_FILE"; then
        echo "Generated installer/gml-manager.sh is out of date. Run installer/build-gml-manager.sh." >&2
        exit 1
    fi
    exit 0
fi

mv "$temporary_file" "$TARGET_FILE"
trap - 0 1 2 15
