#!/bin/sh
# Generated by installer/build-gml-manager.sh. Do not edit directly.

DEFAULT_BASE_DIR="/srv/gml"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-Gml-Launcher/Gml.Backend}"
COMPOSE_URL_OVERRIDE="${COMPOSE_URL:-}"
DEFAULT_COMPOSE_URL="${DEFAULT_COMPOSE_URL:-https://raw.githubusercontent.com/$GITHUB_REPOSITORY/refs/heads/master/docker-compose-installer.yml}"
ENV_URL="${ENV_URL:-https://raw.githubusercontent.com/$GITHUB_REPOSITORY/refs/heads/master/installer/installer.env}"
DEFAULT_TAGS_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/tags?per_page=100"
DNS_DOH_URLS="${DNS_DOH_URLS:-https://dns.google/resolve https://cloudflare-dns.com/dns-query}"

SCRIPT_DIR=""
if [ -f "$0" ]; then
    SCRIPT_DIR=$(CDPATH= cd "$(dirname "$0")" && pwd)
fi

ACTION=""
BASE_DIR=""
VERSION=""
PROXY_MODE=""
PROXY_DOMAIN=""
TARGET_FRONTEND_PORT="5003"
PROXY_HTTPS_PORT="0"
CURRENT_PROXY_MODE="external"
ACCEPT_ACME_TERMS=0
COMPOSE_URL=""
PROMPT_ANSWER=""
INTERACTIVE_MODE=0
SHOW_HELP=0
GML_MANAGER_LANGUAGE="en"
GML_MANAGER_LANGUAGE_EXPLICIT=0

# Return a localized message format. English is the fallback for missing keys.
message_format() {
    language="$1"
    key="$2"

    if [ "$language" = "ru" ]; then
        case "$key" in
            usage_heading) printf '%s' 'Использование:\n' ;;
            usage_install) printf '%s' '  %s install [--version <версия>] [--dir <путь>] [--proxy-mode <external|global>] [--domain <домен>] [--accept-acme-terms] [--lang <ru|en>]\n' ;;
            usage_update) printf '%s' '  %s update [--version <версия>] [--dir <путь>] [--proxy-mode <external|global>] [--domain <домен>] [--accept-acme-terms] [--lang <ru|en>]\n' ;;
            usage_delete) printf '%s' '  %s delete [--dir <путь>] [--lang <ru|en>]\n' ;;
            usage_interactive) printf '%s' '  %s [--lang <ru|en>]\n' ;;
            commands_heading) printf '%s' 'Команды:\n' ;;
            command_install) printf '%s' '  install    Установить Gml.Backend\n' ;;
            command_update) printf '%s' '  update     Обновить Gml.Backend\n' ;;
            command_delete) printf '%s' '  delete     Остановить контейнеры и переместить каталог установки в резервную копию\n' ;;
            options_heading) printf '%s' 'Параметры:\n' ;;
            option_version) printf '%s' '  --version  Переопределить тег версии Docker-образа. Используется для install и update.\n' ;;
            option_dir) printf '%s' '  --dir      Каталог установки. По умолчанию: %s.\n' ;;
            option_lang) printf '%s' '  --lang     Язык интерфейса: ru или en. По умолчанию определяется по локали системы.\n' ;;
            option_proxy_mode) printf '%s' '  --proxy-mode Режим прокси: external (за другим прокси) или global (публичные 80/443 и Let’s Encrypt).\n' ;;
            option_domain) printf '%s' '  --domain   Публичный домен для прокси режима global.\n' ;;
            option_acme_terms) printf '%s' '  --accept-acme-terms Подтвердить условия Let’s Encrypt для прокси режима global.\n' ;;
            option_help) printf '%s' '  -h, --help Показать эту справку.\n' ;;
            error_prefix) printf '%s' '[Gml] Ошибка: %s\n' ;;
            option_requires_value) printf '%s' 'Для параметра %s требуется значение' ;;
            unsupported_language) printf '%s' 'Неподдерживаемый язык: %s. Доступные языки: ru, en' ;;
            language_menu) printf '%b' 'Выберите язык:\n  1) Русский\n  2) English\n' ;;
            language_prompt) printf '%s' 'Язык' ;;
            unknown_command) printf '%s' 'Неизвестная команда: %s' ;;
            unknown_argument) printf '%s' 'Неизвестный аргумент: %s' ;;
            unknown_action) printf '%s' 'Неизвестное действие: %s' ;;
            no_stable_tags) printf '%s' 'По адресу %s не найдены теги стабильных версий\n' ;;
            action_menu) printf '%b' 'Выберите действие:\n  1) установить\n  2) обновить\n  3) удалить\n' ;;
            action_prompt) printf '%s' 'Действие [1]: ' ;;
            installation_directory) printf '%s' 'Каталог установки' ;;
            gml_version) printf '%s' 'Версия Gml' ;;
            proxy_mode_menu) printf '%b' 'Режим прокси:\n  1) external - за существующим прокси\n  2) global - GML будет единственным сервисом на этом сервере и займёт порты 80/443, но автоматически настроит HTTPS и сертификаты\n' ;;
            proxy_mode_prompt) printf '%s' 'Режим прокси' ;;
            proxy_domain_prompt) printf '%s' 'Публичный домен для панели' ;;
            acme_terms_prompt) printf '%s' 'Вы принимаете условия Let’s Encrypt? [y/N]: ' ;;
            invalid_proxy_mode) printf '%s' 'Неподдерживаемый режим прокси: %s. Допустимы external и global' ;;
            invalid_domain) printf '%s' 'Некорректный домен: %s. Укажите один FQDN без схемы (http[s]://), пути и порта' ;;
            invalid_port) printf '%s' 'Некорректный HTTP-порт прокси: %s. Допустимы значения от 1 до 65535' ;;
            domain_required) printf '%s' 'Для режима global требуется --domain' ;;
            acme_terms_required) printf '%s' 'Для включения режима global подтвердите условия Let’s Encrypt через --accept-acme-terms' ;;
            latest_version_error) printf '%s' 'Не удалось определить последнюю стабильную версию на GitHub. Передайте --version, чтобы использовать конкретную версию.' ;;
            using_latest_version) printf '%s' '[Gml] Используется последняя стабильная версия: %s\n' ;;
            root_required) printf '%s' 'Этот скрипт необходимо запустить от имени root' ;;
            step_failed) printf '%s' '[Gml] Шаг завершился с ошибкой: %s (код выхода %s)\n' ;;
            last_log_lines) printf '%s' '[Gml] Последние строки журнала:\n' ;;
            no_package_manager) printf '%s' 'Не найден поддерживаемый менеджер пакетов\n' ;;
            directory_not_empty) printf '%s' 'Каталог установки не пуст: %s\n' ;;
            choose_empty_directory) printf '%s' 'Выберите пустой каталог или удалите существующее содержимое перед установкой.\n' ;;
            directory_missing) printf '%s' 'Каталог установки не существует: %s\n' ;;
            compose_overwrite_warning) printf '%s' '[Gml] Внимание: docker-compose.yml будет заменён актуальным шаблоном, а ручные изменения в этом файле будут потеряны.\nВы готовы продолжить обновление? [y/N]: ' ;;
            update_cancelled) printf '%s' '[Gml] Обновление отменено. Файлы не изменены.\n' ;;
            openssl_required) printf '%s' 'Для создания SECURITY_KEY требуется openssl\n' ;;
            backend_ready) printf '%s' 'Gml.Backend готов к работе' ;;
            admin_panel) printf '%s' 'Панель администратора:' ;;
            backend_removed) printf '%s' 'Gml.Backend удалён, каталог сохранён в резервной копии' ;;
            step_detect_os) printf '%s' '[Gml] Определение операционной системы' ;;
            step_prepare_os) printf '%s' '[Gml] Подготовка операционной системы' ;;
            step_install_curl) printf '%s' '[Gml] Установка curl' ;;
            step_install_openssl) printf '%s' '[Gml] Установка openssl' ;;
            step_install_docker) printf '%s' '[Gml] Установка Docker' ;;
            step_install_network_tools) printf '%s' '[Gml] Установка сетевых инструментов' ;;
            step_check_proxy) printf '%s' '[Gml] Проверка домена и портов прокси' ;;
            step_check_empty_directory) printf '%s' '[Gml] Проверка, что каталог установки пуст' ;;
            step_check_directory) printf '%s' '[Gml] Проверка каталога установки' ;;
            step_create_directory) printf '%s' '[Gml] Создание каталога установки' ;;
            step_download_compose) printf '%s' '[Gml] Загрузка docker-compose.yml' ;;
            step_update_env) printf '%s' '[Gml] Создание или обновление .env' ;;
            step_start_compose) printf '%s' '[Gml] Запуск docker compose' ;;
            step_stop_compose) printf '%s' '[Gml] Остановка docker compose' ;;
            step_stop_compose_volumes) printf '%s' '[Gml] Остановка docker compose и удаление томов' ;;
            step_remove_images) printf '%s' '[Gml] Удаление Docker-образов' ;;
            step_backup_directory) printf '%s' '[Gml] Создание резервной копии каталога установки' ;;
            *) message_format "en" "$key" ;;
        esac
        return
    fi

    case "$key" in
        usage_heading) printf '%s' 'Usage:\n' ;;
        usage_install) printf '%s' '  %s install [--version <version>] [--dir <path>] [--proxy-mode <external|global>] [--domain <domain>] [--accept-acme-terms] [--lang <ru|en>]\n' ;;
        usage_update) printf '%s' '  %s update [--version <version>] [--dir <path>] [--proxy-mode <external|global>] [--domain <domain>] [--accept-acme-terms] [--lang <ru|en>]\n' ;;
        usage_delete) printf '%s' '  %s delete [--dir <path>] [--lang <ru|en>]\n' ;;
        usage_interactive) printf '%s' '  %s [--lang <ru|en>]\n' ;;
        commands_heading) printf '%s' 'Commands:\n' ;;
        command_install) printf '%s' '  install    Install Gml.Backend\n' ;;
        command_update) printf '%s' '  update     Update Gml.Backend\n' ;;
        command_delete) printf '%s' '  delete     Stop containers and move the install directory to a backup\n' ;;
        options_heading) printf '%s' 'Options:\n' ;;
        option_version) printf '%s' '  --version  Override Docker image version tag. Used by install and update.\n' ;;
        option_dir) printf '%s' '  --dir      Installation directory. Defaults to %s.\n' ;;
        option_lang) printf '%s' '  --lang     Interface language: ru or en. Defaults to the system locale.\n' ;;
        option_proxy_mode) printf '%s' '  --proxy-mode Proxy mode: external (behind another proxy) or global (public ports 80/443 and Let’s Encrypt).\n' ;;
        option_domain) printf '%s' '  --domain   Public domain for global mode.\n' ;;
        option_acme_terms) printf '%s' '  --accept-acme-terms Accept the Let’s Encrypt terms when enabling global non-interactively.\n' ;;
        option_help) printf '%s' '  -h, --help Show this help.\n' ;;
        error_prefix) printf '%s' '[Gml] Error: %s\n' ;;
        option_requires_value) printf '%s' '%s requires a value' ;;
        unsupported_language) printf '%s' 'Unsupported language: %s. Available languages: ru, en' ;;
        language_menu) printf '%b' 'Select language:\n  1) Русский\n  2) English\n' ;;
        language_prompt) printf '%s' 'Language' ;;
        unknown_command) printf '%s' 'Unknown command: %s' ;;
        unknown_argument) printf '%s' 'Unknown argument: %s' ;;
        unknown_action) printf '%s' 'Unknown action: %s' ;;
        no_stable_tags) printf '%s' 'No stable version tags found at %s\n' ;;
        action_menu) printf '%b' 'Select action:\n  1) install\n  2) update\n  3) delete\n' ;;
        action_prompt) printf '%s' 'Action [1]: ' ;;
        installation_directory) printf '%s' 'Installation directory' ;;
        gml_version) printf '%s' 'Gml version' ;;
        proxy_mode_menu) printf '%b' 'Proxy mode:\n  1) external - behind an existing proxy\n  2) global - GML will be the sole service on this server, utilizing ports 80/443, but it will set up HTTPS and certificates automatically\n' ;;
        proxy_mode_prompt) printf '%s' 'Proxy mode' ;;
        proxy_domain_prompt) printf '%s' 'Public domain for panel' ;;
        acme_terms_prompt) printf '%s' 'Do you accept the Let’s Encrypt terms? [y/N]: ' ;;
        invalid_proxy_mode) printf '%s' 'Unsupported proxy mode: %s. Use external or global' ;;
        invalid_domain) printf '%s' 'Invalid domain: %s. Specify one regular FQDN without a scheme (http[s]://), path or port' ;;
        invalid_port) printf '%s' 'Invalid proxy HTTP port: %s. Use a value from 1 to 65535' ;;
        domain_required) printf '%s' 'Global mode requires --domain' ;;
        acme_terms_required) printf '%s' 'To enable global mode, accept the Let’s Encrypt terms with --accept-acme-terms' ;;
        latest_version_error) printf '%s' 'Unable to resolve the latest stable version from GitHub. Pass --version to use a specific version.' ;;
        using_latest_version) printf '%s' '[Gml] Using latest stable version: %s\n' ;;
        root_required) printf '%s' 'This script must be run as root' ;;
        step_failed) printf '%s' '[Gml] Step failed: %s (exit code %s)\n' ;;
        last_log_lines) printf '%s' '[Gml] Last log lines:\n' ;;
        no_package_manager) printf '%s' 'No supported package manager found\n' ;;
        directory_not_empty) printf '%s' 'Installation directory is not empty: %s\n' ;;
        choose_empty_directory) printf '%s' 'Choose an empty directory or remove the existing contents before installing.\n' ;;
        directory_missing) printf '%s' 'Installation directory does not exist: %s\n' ;;
        compose_overwrite_warning) printf '%s' '[Gml] Warning: docker-compose.yml will be replaced with the current template, and manual changes in this file will be lost.\nAre you ready to continue with the update? [y/N]: ' ;;
        update_cancelled) printf '%s' '[Gml] Update cancelled. No files were changed.\n' ;;
        openssl_required) printf '%s' 'openssl is required to generate SECURITY_KEY\n' ;;
        backend_ready) printf '%s' 'Gml.Backend is ready' ;;
        admin_panel) printf '%s' 'Admin panel:' ;;
        backend_removed) printf '%s' 'Gml.Backend was removed and backed up' ;;
        step_detect_os) printf '%s' '[Gml] Detecting operating system' ;;
        step_prepare_os) printf '%s' '[Gml] Preparing operating system' ;;
        step_install_curl) printf '%s' '[Gml] Installing curl' ;;
        step_install_openssl) printf '%s' '[Gml] Installing openssl' ;;
        step_install_docker) printf '%s' '[Gml] Installing Docker' ;;
        step_install_network_tools) printf '%s' '[Gml] Installing network tools' ;;
        step_check_proxy) printf '%s' '[Gml] Checking proxy domain and ports' ;;
        step_check_empty_directory) printf '%s' '[Gml] Checking installation directory is empty' ;;
        step_check_directory) printf '%s' '[Gml] Checking installation directory' ;;
        step_create_directory) printf '%s' '[Gml] Creating installation directory' ;;
        step_download_compose) printf '%s' '[Gml] Downloading docker-compose.yml' ;;
        step_update_env) printf '%s' '[Gml] Creating or updating .env' ;;
        step_start_compose) printf '%s' '[Gml] Starting docker compose' ;;
        step_stop_compose) printf '%s' '[Gml] Stopping docker compose' ;;
        step_stop_compose_volumes) printf '%s' '[Gml] Stopping docker compose and volumes' ;;
        step_remove_images) printf '%s' '[Gml] Removing Docker images' ;;
        step_backup_directory) printf '%s' '[Gml] Backing up installation directory' ;;
        *) printf '%s' "$key" ;;
    esac
}

# Print a translated message using the selected language and optional arguments.
message() {
    key="$1"
    shift
    # The sentinel preserves trailing newlines that command substitution removes.
    format=$(message_format "$GML_MANAGER_LANGUAGE" "$key"; printf '_')
    format=${format%_}
    # shellcheck disable=SC2059 -- the format comes from the built-in dictionary.
    printf "$format" "$@"
}

# Set one of the explicitly supported interface languages.
set_language() {
    case "$1" in
        ru|en)
            GML_MANAGER_LANGUAGE="$1"
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

# Pick a language from the highest-priority locale environment variable.
set_language_from_environment() {
    locale_name=${LC_ALL:-${LC_MESSAGES:-${LANG:-}}}

    case "$locale_name" in
        ru|ru_*|ru.*|ru-*) GML_MANAGER_LANGUAGE="ru" ;;
        *) GML_MANAGER_LANGUAGE="en" ;;
    esac
}

# Pre-scan arguments so --lang affects help and argument parsing errors.
detect_language() {
    requested_language=""
    GML_MANAGER_LANGUAGE_EXPLICIT=0

    while [ "$#" -gt 0 ]; do
        if [ "$1" = "--lang" ] && [ "$#" -gt 1 ]; then
            requested_language="$2"
            shift 2
        else
            shift
        fi
    done

    if [ -n "$requested_language" ] && set_language "$requested_language"; then
        GML_MANAGER_LANGUAGE_EXPLICIT=1
        return 0
    fi

    set_language_from_environment
}

# Print the GML Manager banner when the script starts.
print_banner() {
    cat <<'EOF'

 ██████╗ ███╗   ███╗██╗         ███╗   ███╗ █████╗ ███╗   ██╗ █████╗  ██████╗ ███████╗██████╗ 
██╔════╝ ████╗ ████║██║         ████╗ ████║██╔══██╗████╗  ██║██╔══██╗██╔════╝ ██╔════╝██╔══██╗
██║  ███╗██╔████╔██║██║         ██╔████╔██║███████║██╔██╗ ██║███████║██║  ███╗█████╗  ██████╔╝
██║   ██║██║╚██╔╝██║██║         ██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║   ██║██╔══╝  ██╔══██╗
╚██████╔╝██║ ╚═╝ ██║███████╗    ██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║╚██████╔╝███████╗██║  ██║
 ╚═════╝ ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝
                                                                                               
EOF
}

# Print command-line usage for both scripted and interactive workflows.
print_usage() {
    message usage_heading
    message usage_install "$0"
    message usage_update "$0"
    message usage_delete "$0"
    message usage_interactive "$0"
    printf '\n'
    message commands_heading
    message command_install
    message command_update
    message command_delete
    printf '\n'
    message options_heading
    message option_version
    message option_dir "$DEFAULT_BASE_DIR"
    message option_proxy_mode
    message option_domain
    message option_acme_terms
    message option_lang
    message option_help
}

# Stop immediately with a consistent error prefix.
error() {
    message error_prefix "$*" >&2
    exit 1
}

# Validate that an option expecting a value actually received one.
require_value() {
    option="$1"
    value="${2:-}"

    if [ -z "$value" ]; then
        error "$(message option_requires_value "$option")"
    fi
}

# Parse the optional command and flags before any privileged work starts.
parse_args() {
    if [ "$#" -eq 0 ]; then
        INTERACTIVE_MODE=1
        return 0
    fi

    while [ "$#" -gt 0 ]; do
        case "$1" in
            install)
                if [ -n "$ACTION" ]; then
                    error "$(message unknown_argument "$1")"
                fi
                ACTION="install"
                shift
                ;;
            update)
                if [ -n "$ACTION" ]; then
                    error "$(message unknown_argument "$1")"
                fi
                ACTION="update"
                shift
                ;;
            delete)
                if [ -n "$ACTION" ]; then
                    error "$(message unknown_argument "$1")"
                fi
                ACTION="delete"
                shift
                ;;
            --version)
                require_value "$1" "${2:-}"
                VERSION="$2"
                shift 2
                ;;
            --dir)
                require_value "$1" "${2:-}"
                BASE_DIR="$2"
                shift 2
                ;;
            --proxy-mode)
                require_value "$1" "${2:-}"
                PROXY_MODE="$2"
                shift 2
                ;;
            --domain)
                require_value "$1" "${2:-}"
                PROXY_DOMAIN="$2"
                shift 2
                ;;
            --accept-acme-terms)
                ACCEPT_ACME_TERMS=1
                shift
                ;;
            --lang)
                require_value "$1" "${2:-}"
                if ! set_language "$2"; then
                    error "$(message unsupported_language "$2")"
                fi
                shift 2
                ;;
            -h|--help)
                SHOW_HELP=1
                shift
                ;;
            *)
                if [ -z "$ACTION" ]; then
                    error "$(message unknown_command "$1")"
                fi
                error "$(message unknown_argument "$1")"
                ;;
        esac
    done

    if [ "$SHOW_HELP" -eq 1 ]; then
        print_usage
        exit 0
    fi

    if [ -z "$ACTION" ]; then
        INTERACTIVE_MODE=1
    fi
}

# Extract the greatest stable numeric tag (vN.N[.N...]) from GitHub tags JSON.
extract_latest_stable_tag() {
    sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | awk '
        {
            tag = $0

            if (tag !~ /^v/) {
                next
            }

            version = tag
            sub(/^v/, "", version)
            part_count = split(version, parts, ".")

            if (part_count < 2) {
                next
            }

            valid = 1
            for (i = 1; i <= part_count; i++) {
                if (parts[i] !~ /^[0-9][0-9]*$/) {
                    valid = 0
                }
            }

            if (valid == 0) {
                next
            }

            is_better = 0

            if (found == 0) {
                is_better = 1
            } else {
                max_part_count = part_count > best_part_count ? part_count : best_part_count

                for (i = 1; i <= max_part_count; i++) {
                    current_part = i <= part_count ? parts[i] + 0 : 0
                    best_part = i <= best_part_count ? best_parts[i] : 0

                    if (current_part > best_part) {
                        is_better = 1
                        break
                    }

                    if (current_part < best_part) {
                        break
                    }

                    if (i == max_part_count && part_count > best_part_count) {
                        is_better = 1
                    }
                }
            }

            if (is_better == 1) {
                found = 1
                best_tag = tag
                best_part_count = part_count

                for (i = 1; i <= best_part_count; i++) {
                    delete best_parts[i]
                }
                for (i = 1; i <= part_count; i++) {
                    best_parts[i] = parts[i] + 0
                }
            }
        }
        END {
            if (found == 1) {
                print best_tag
            } else {
                exit 1
            }
        }
    '
}

# Fetch the latest stable release tag from GitHub, or from an override URL in tests.
fetch_latest_stable_version() {
    tags_url="${GML_MANAGER_TAGS_URL:-$DEFAULT_TAGS_URL}"
    latest_version=$(curl -fsSL "$tags_url" | extract_latest_stable_tag)

    if [ -z "$latest_version" ]; then
        message no_stable_tags "$tags_url" >&2
        return 1
    fi

    printf "%s\n" "$latest_version"
}

# Read an answer from the terminal even when the script body is piped through stdin.
read_prompt_answer() {
    PROMPT_ANSWER=""

    if [ -e /dev/tty ] && { IFS= read -r PROMPT_ANSWER < /dev/tty; } 2>/dev/null; then
        return 0
    fi

    # Also accept redirected stdin for CI and other explicitly scripted input.
    IFS= read -r PROMPT_ANSWER || PROMPT_ANSWER=""
}

# Read a value while keeping a safe default for empty input.
prompt_with_default() {
    prompt="$1"
    default="$2"

    printf "%s [%s]: " "$prompt" "$default" >&2
    read_prompt_answer

    if [ -z "$PROMPT_ANSWER" ]; then
        PROMPT_ANSWER="$default"
    fi
}

# Let interactive users confirm or override the language inferred from locale.
prompt_language() {
    message language_menu >&2
    prompt_with_default "$(message language_prompt)" "$GML_MANAGER_LANGUAGE"

    case "$PROMPT_ANSWER" in
        1|ru) set_language "ru" ;;
        2|en) set_language "en" ;;
        *) error "$(message unsupported_language "$PROMPT_ANSWER")" ;;
    esac
}

# Keep an explicit --lang value; otherwise ask only in the interactive workflow.
resolve_language_input() {
    if [ "$INTERACTIVE_MODE" -eq 1 ] && [ "$GML_MANAGER_LANGUAGE_EXPLICIT" -eq 0 ]; then
        prompt_language
    fi
}

# Interactive action selector used when the script is launched without a command.
prompt_action() {
    message action_menu >&2
    message action_prompt >&2
    read_prompt_answer

    case "${PROMPT_ANSWER:-1}" in
        1|install)
            ACTION="install"
            ;;
        2|update)
            ACTION="update"
            ;;
        3|delete)
            ACTION="delete"
            ;;
        *)
            error "$(message unknown_action "$PROMPT_ANSWER")"
            ;;
    esac
}

# Updating replaces the managed Compose template. Require an explicit answer so
# manual edits are never discarded merely because an update command was run.
confirm_compose_overwrite() {
    message compose_overwrite_warning >&2
    read_prompt_answer

    case "$PROMPT_ANSWER" in
        y|Y|yes|YES|Yes|д|Д|да|ДА|Да)
            return 0
            ;;
        *)
            message update_cancelled >&2
            return 1
            ;;
    esac
}


# Resolve missing action and directory inputs through interactive prompts.
resolve_action_and_base_dir() {
    if [ -z "$ACTION" ]; then
        prompt_action
    fi

    if [ -z "$BASE_DIR" ]; then
        prompt_with_default "$(message installation_directory)" "$DEFAULT_BASE_DIR"
        BASE_DIR="$PROMPT_ANSWER"
    fi
}


# Ask proxy mode
prompt_proxy_settings() {
    message proxy_mode_menu >&2
    prompt_with_default "$(message proxy_mode_prompt)" "$CURRENT_PROXY_MODE"

    case "$PROMPT_ANSWER" in
        1|external) PROXY_MODE="external" ;;
        2|global) PROXY_MODE="global" ;;
        *) error "$(message invalid_proxy_mode "$PROMPT_ANSWER")" ;;
    esac

    if [ "$PROXY_MODE" = "global" ]; then
        default_domain=$(get_env_value "$BASE_DIR/.env" "GML_PROXY_DOMAIN")
        prompt_with_default "$(message proxy_domain_prompt)" "${default_domain:-gml.example.com}"
        PROXY_DOMAIN="$PROMPT_ANSWER"

        if [ "$CURRENT_PROXY_MODE" != "global" ]; then
            message acme_terms_prompt >&2
            read_prompt_answer
            case "$PROMPT_ANSWER" in
                y|Y|yes|YES|Yes|д|Д|да|ДА|Да) ACCEPT_ACME_TERMS=1 ;;
                *) error "$(message acme_terms_required)" ;;
            esac
        fi
    fi
}

resolve_proxy_inputs() {
    if [ "$ACTION" = "delete" ]; then
        return 0
    fi

    installed_mode=$(get_env_value "$BASE_DIR/.env" "GML_PROXY_MODE")
    case "$installed_mode" in
        global) CURRENT_PROXY_MODE="global" ;;
        *) CURRENT_PROXY_MODE="external" ;;
    esac

    if [ "$ACTION" = "install" ]; then
        CURRENT_PROXY_MODE="external"
    fi

    if [ "$INTERACTIVE_MODE" -eq 1 ]; then
        prompt_proxy_settings
    elif [ -z "$PROXY_MODE" ]; then
        if [ "$ACTION" = "update" ]; then
            PROXY_MODE="$CURRENT_PROXY_MODE"
        else
            PROXY_MODE="external"
        fi
    fi

    case "$PROXY_MODE" in
        external)
            PROXY_DOMAIN=""
            PROXY_HTTPS_PORT="0"
            if [ "$CURRENT_PROXY_MODE" = "external" ]; then
                TARGET_FRONTEND_PORT=$(get_env_value "$BASE_DIR/.env" "PORT_GML_FRONTEND")
                TARGET_FRONTEND_PORT=${TARGET_FRONTEND_PORT:-5003}
            else
                TARGET_FRONTEND_PORT="5003"
            fi
            is_valid_port "$TARGET_FRONTEND_PORT" || error "$(message invalid_port "$TARGET_FRONTEND_PORT")"
            ;;
        global)
            if [ -z "$PROXY_DOMAIN" ]; then
                PROXY_DOMAIN=$(get_env_value "$BASE_DIR/.env" "GML_PROXY_DOMAIN")
            fi
            PROXY_DOMAIN=$(printf '%s' "$PROXY_DOMAIN" | tr '[:upper:]' '[:lower:]')
            [ -n "$PROXY_DOMAIN" ] || error "$(message domain_required)"
            validate_proxy_domain "$PROXY_DOMAIN" || error "$(message invalid_domain "$PROXY_DOMAIN")"

            if [ "$CURRENT_PROXY_MODE" != "global" ] && [ "$ACCEPT_ACME_TERMS" -ne 1 ]; then
                error "$(message acme_terms_required)"
            fi
            TARGET_FRONTEND_PORT="80"
            PROXY_HTTPS_PORT="443"
            ;;
        *)
            error "$(message invalid_proxy_mode "$PROXY_MODE")"
            ;;
    esac

    COMPOSE_URL=${COMPOSE_URL_OVERRIDE:-$DEFAULT_COMPOSE_URL}
}

# Resolve the version through GitHub unless the user provided an explicit override.
resolve_version_input() {
    case "$ACTION" in
        install|update)
            if [ -z "$VERSION" ]; then
                latest_version=$(fetch_latest_stable_version) || error "$(message latest_version_error)"

                if [ "$INTERACTIVE_MODE" -eq 1 ]; then
                    prompt_with_default "$(message gml_version)" "$latest_version"
                    VERSION="$PROMPT_ANSWER"
                else
                    VERSION="$latest_version"
                    message using_latest_version "$VERSION" >&2
                fi
            fi
            ;;
        delete)
            ;;
        *)
            error "$(message unknown_action "$ACTION")"
            ;;
    esac
}

# Accept a single ASCII hostname.
validate_proxy_domain() {
    domain="$1"

    [ "${#domain}" -le 253 ] || return 1
    is_ipv4 "$domain" && return 1

    printf '%s\n' "$domain" | LC_ALL=C awk '
        NR != 1 || index($0, ".") == 0 { exit 1 }

        {
            count = split($0, labels, ".")
            for (i = 1; i <= count; i++) {
                if (length(labels[i]) > 63 ||
                    labels[i] !~ /^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$/) {
                    exit 1
                }
            }
        }
    '
}

is_valid_port() {
    case "$1" in
        ""|*[!0-9]*) return 1 ;;
    esac

    printf '%s\n' "$1" | awk '{ exit !($0 + 0 >= 1 && $0 + 0 <= 65535) }'
}


is_ipv4() {
    printf '%s\n' "$1" | awk -F. '
        NF != 4 { exit 1 }
        {
            for (i = 1; i <= 4; i++) {
                if ($i !~ /^[0-9]+$/ || $i < 0 || $i > 255) exit 1
            }
        }
    '
}

# Query several independent services so a temporary outage does not prevent installation. 
# IPv4 is authoritative for the mandatory DNS A check.
detect_public_ipv4() {
    for endpoint in https://ifconfig.me/ip https://api.ipify.org https://icanhazip.com; do
        address=$(curl -4 -fsS --connect-timeout 3 --max-time 7 "$endpoint" 2>/dev/null | tr -d '[:space:]') || address=""
        if [ -n "$address" ] && is_ipv4 "$address"; then
            printf '%s\n' "$address"
            return 0
        fi
    done

    echo "Unable to determine the server public IPv4 address" >&2
    return 1
}

detect_public_ipv6() {
    for endpoint in https://ifconfig.me/ip https://api64.ipify.org https://icanhazip.com; do
        address=$(curl -6 -fsS --connect-timeout 3 --max-time 7 "$endpoint" 2>/dev/null | tr -d '[:space:]') || address=""
        case "$address" in
            *:*) printf '%s\n' "$address"; return 0 ;;
        esac
    done

    return 1
}

# Canonicalize equivalent IPv6 spellings (expanded/compressed, letter case)
# when libc getent is available; fall back to lowercase text otherwise.
normalize_ipv6() {
    normalized=""
    if command -v getent >/dev/null 2>&1; then
        normalized=$(getent ahostsv6 "$1" 2>/dev/null | awk 'NR == 1 { print $1 }')
    fi
    printf '%s\n' "${normalized:-$1}" | tr '[:upper:]' '[:lower:]'
}

# Extract address records from the compact or pretty-printed JSON returned by the Google and Cloudflare DNS-over-HTTPS APIs.
parse_doh_records() {
    response="$1"
    rr_number="$2"

    printf '%s' "$response" | awk -v RS='}' -v rr_number="$rr_number" '
        $0 ~ "\"type\"[[:space:]]*:[[:space:]]*" rr_number "([^0-9]|$)" &&
        match($0, /"data"[[:space:]]*:[[:space:]]*"[^"]*"/) {
            value = substr($0, RSTART, RLENGTH)
            sub(/^"data"[[:space:]]*:[[:space:]]*"/, "", value)
            sub(/"$/, "", value)
            print value
        }
    '
}

# Resolve through public DNS-over-HTTPS endpoints using curl, which the installer already requires. The optional URL list makes the check mockable.
query_doh_records() {
    record_type="$1"
    rr_number="$2"

    for doh_url in $DNS_DOH_URLS; do
        doh_response=$(curl -fsS --connect-timeout 3 --max-time 7 \
            --header 'accept: application/dns-json' \
            --get --data-urlencode "name=$PROXY_DOMAIN" --data "type=$record_type" \
            "$doh_url" 2>/dev/null) || continue

        if printf '%s' "$doh_response" | grep -Eq '"Status"[[:space:]]*:[[:space:]]*0([^0-9]|$)'; then
            parse_doh_records "$doh_response" "$rr_number"
            return 0
        fi
    done

    echo "Unable to query public DNS for $PROXY_DOMAIN $record_type records" >&2
    return 1
}

# Let's Encrypt must reach this exact machine. Proxy/CDN records are rejected
# because they require a different challenge and trusted-proxy configuration.
check_global_dns() {
    public_ipv4=$(detect_public_ipv4) || return 1
    a_records=$(query_doh_records A 1) || return 1

    if [ -z "$a_records" ]; then
        echo "Domain $PROXY_DOMAIN has no DNS A record" >&2
        return 1
    fi

    for address in $a_records; do
        if ! is_ipv4 "$address" || [ "$address" != "$public_ipv4" ]; then
            echo "DNS A for $PROXY_DOMAIN points to $address, but this server public IPv4 is $public_ipv4" >&2
            echo "Cloudflare/CDN proxying is not supported in global mode; use a direct DNS record" >&2
            return 1
        fi
    done

    aaaa_records=$(query_doh_records AAAA 28) || return 1
    if [ -n "$aaaa_records" ]; then
        public_ipv6=$(detect_public_ipv6) || {
            echo "Domain $PROXY_DOMAIN has an AAAA record, but this server has no detectable public IPv6" >&2
            echo "Point every AAAA record to this server or remove AAAA before requesting a certificate" >&2
            return 1
        }

        for address in $aaaa_records; do
            if [ "$(normalize_ipv6 "$address")" != "$(normalize_ipv6 "$public_ipv6")" ]; then
                echo "DNS AAAA for $PROXY_DOMAIN points to $address, but this server public IPv6 is $public_ipv6" >&2
                echo "Point every AAAA record to this server or remove AAAA before requesting a certificate" >&2
                return 1
            fi
        done
    fi

    echo "DNS A: $PROXY_DOMAIN -> $public_ipv4"
}

check_port_available() {
    port="$1"
    listening_sockets=$(ss -H -ltn 2>/dev/null) || {
        echo "Unable to inspect listening TCP ports with ss" >&2
        return 1
    }

    if printf '%s\n' "$listening_sockets" | awk -v port="$port" '
        {
            address = $4
            sub(/^.*:/, "", address)
            if (address == port) found = 1
        }
        END { exit found ? 0 : 1 }
    '; then
        echo "TCP port $port is already in use:" >&2
        ss -H -ltnp 2>/dev/null | awk -v port="$port" '$4 ~ (":" port "$")' >&2 || true
        return 1
    fi
}

# A running installation owns its current ports, so availability is checked for
# fresh installs and mode transitions only. DNS is checked on every global run.
check_proxy_requirements() {
    if [ "$PROXY_MODE" = "global" ]; then
        check_global_dns || return 1
    fi

    if [ "$ACTION" = "update" ] && [ "$PROXY_MODE" = "$CURRENT_PROXY_MODE" ]; then
        return 0
    fi

    if [ "$PROXY_MODE" = "global" ]; then
        check_port_available 80 || return 1
        check_port_available 443 || return 1
    else
        check_port_available "$TARGET_FRONTEND_PORT" || return 1
    fi
}


# Root is required because the script installs packages and controls Docker.
require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        error "$(message root_required)"
    fi
}

# Display a lightweight spinner while a background step is running.
show_spinner() {
    pid="$1"
    text="$2"
    delay=0.1

    while kill -0 "$pid" 2>/dev/null; do
        for char in "/" "-" "\\" "|"; do
            printf "\r%s %s" "$text" "$char"
            sleep "$delay"
            if ! kill -0 "$pid" 2>/dev/null; then
                break
            fi
        done
    done

    wait "$pid"
    result="$?"

    if [ "$result" -eq 0 ]; then
        printf "\r%s \033[32m✓\033[0m\n" "$text"
    else
        printf "\r%s \033[31m✗\033[0m\n" "$text"
    fi

    return "$result"
}

# Run one step, capture its log, and abort the whole flow on failure.
run_step() {
    text="$1"
    shift
    log_file=$(mktemp "${TMPDIR:-/tmp}/gml-manager.XXXXXX") || exit 1

    (
        "$@"
    ) >"$log_file" 2>&1 &

    show_spinner "$!" "$text"
    result="$?"

    if [ "$result" -ne 0 ]; then
        message step_failed "$text" "$result" >&2
        if [ -s "$log_file" ]; then
            message last_log_lines >&2
            tail -n 40 "$log_file" >&2
        fi
        rm -f "$log_file"
        exit "$result"
    fi

    rm -f "$log_file"
}

# Avoid interactive package restart prompts on systems with needrestart.
disable_additional_notify() {
    if [ -f /etc/needrestart/needrestart.conf ]; then
        sed -i "s/#\$nrconf{restart} = 'i';/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
    fi
}

# Record OS information in the step log for easier troubleshooting.
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        echo "OS: ${NAME:-unknown} ${VERSION_ID:-unknown}"
    else
        echo "OS: unknown"
    fi
}

# Detect Alpine because Docker is installed from Alpine packages there.
is_alpine() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        [ "${ID:-}" = "alpine" ]
        return "$?"
    fi

    return 1
}

# Install a package through the first supported package manager found.
install_package() {
    package="$1"

    if command -v apk >/dev/null 2>&1; then
        apk add --no-cache "$package"
    elif command -v apt-get >/dev/null 2>&1; then
        apt-get update
        apt-get install -y "$package"
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y "$package"
    elif command -v yum >/dev/null 2>&1; then
        yum install -y "$package"
    elif command -v zypper >/dev/null 2>&1; then
        zypper install -y "$package"
    elif command -v pacman >/dev/null 2>&1; then
        pacman -Sy --noconfirm "$package"
    else
        message no_package_manager >&2
        return 1
    fi
}

# Confirm the Docker Compose plugin exists.
docker_compose_available() {
    docker compose version >/dev/null 2>&1
}

# Ensure a command exists, installing its package when needed.
ensure_command() {
    command_name="$1"
    package_name="$2"

    if ! command -v "$command_name" >/dev/null 2>&1; then
        install_package "$package_name"
    fi
}

# Install the package that provides ss on the detected distribution.
ensure_socket_tools() {
    command -v ss >/dev/null 2>&1 && return 0

    if command -v dnf >/dev/null 2>&1 || command -v yum >/dev/null 2>&1; then
        install_package iproute
    else
        install_package iproute2
    fi
}


# Start Docker across common Linux init systems.
start_docker_service() {
    if command -v systemctl >/dev/null 2>&1; then
        systemctl enable --now docker
    elif command -v rc-update >/dev/null 2>&1 && command -v rc-service >/dev/null 2>&1; then
        rc-update add docker default
        rc-service docker start
    elif command -v service >/dev/null 2>&1; then
        service docker start
    fi
}

# Install Docker from Alpine packages, including the Compose plugin.
install_alpine_docker() {
    apk add --no-cache docker docker-cli-compose || return 1
    start_docker_service
}

# Install Docker through the official convenience script and start the service.
install_docker() {
    if command -v docker >/dev/null 2>&1 && docker_compose_available; then
        return 0
    fi

    if is_alpine; then
        install_alpine_docker
    else
        sh -c "$(curl -fsSL https://get.docker.com)"
        start_docker_service
    fi

    docker_compose_available
}


# Read a simple KEY=value entry from an existing .env file.
get_env_value() {
    env_file="$1"
    key="$2"

    if [ ! -f "$env_file" ]; then
        return 0
    fi

    sed -n "s/^${key}=//p" "$env_file" | tail -n 1
}


# Create the selected installation directory.
prepare_directory() {
    mkdir -p "$BASE_DIR"
}

# New installations must start from an empty or missing directory.
ensure_install_directory_empty() {
    if [ ! -d "$BASE_DIR" ]; then
        return 0
    fi

    if find "$BASE_DIR" -mindepth 1 -maxdepth 1 | grep -q .; then
        message directory_not_empty "$BASE_DIR" >&2
        message choose_empty_directory >&2
        return 1
    fi
}

# Updates and removals must target an existing installation directory.
ensure_install_directory_exists() {
    if [ ! -d "$BASE_DIR" ]; then
        message directory_missing "$BASE_DIR" >&2
        return 1
    fi
}

# Download the production compose template into the installation directory.
download_compose() {
    mkdir -p "$BASE_DIR"
    cd "$BASE_DIR"
    curl -fsSL "$COMPOSE_URL" -o docker-compose.yml
}

# Generate the SECURITY_KEY value for a new installation.
generate_security_key() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
        return 0
    fi

    message openssl_required >&2
    return 1
}

# Copy the bundled .env template, or download it when this script is piped to sh.
copy_env_template() {
    env_file="$1"

    if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/installer.env" ]; then
        cp "$SCRIPT_DIR/installer.env" "$env_file"
        return 0
    fi

    curl -fsSL "$ENV_URL" -o "$env_file"
}

# Create the initial .env file without overwriting future user changes.
write_default_env() {
    env_file="$BASE_DIR/.env"
    security_key=$(generate_security_key) || return 1

    copy_env_template "$env_file" || return 1
    upsert_env_value "$env_file" "GML_VERSION" "$VERSION"
    upsert_env_value "$env_file" "GML_PROXY_MODE" "$PROXY_MODE"
    upsert_env_value "$env_file" "GML_PROXY_DOMAIN" "$PROXY_DOMAIN"
    upsert_env_value "$env_file" "GML_PROXY_HTTPS_PORT" "$PROXY_HTTPS_PORT"
    upsert_env_value "$env_file" "PORT_GML_FRONTEND" "$TARGET_FRONTEND_PORT"
    upsert_env_value "$env_file" "SECURITY_KEY" "$security_key"
}

# Insert or update one KEY=value entry while preserving all other .env lines.
upsert_env_value() {
    env_file="$1"
    key="$2"
    value="$3"
    tmp_file="${env_file}.tmp.$$"

    if [ ! -f "$env_file" ]; then
        printf "%s=%s\n" "$key" "$value" > "$env_file"
        return 0
    fi

    awk -v key="$key" -v value="$value" '
        BEGIN { found = 0 }
        $0 ~ "^" key "=" {
            print key "=" value
            found = 1
            next
        }
        { print }
        END {
            if (found == 0) {
                print key "=" value
            }
        }
    ' "$env_file" > "$tmp_file"

    mv "$tmp_file" "$env_file"
}

# Create .env on first install or update installer-managed values afterwards.
ensure_env() {
    if [ ! -f "$BASE_DIR/.env" ]; then
        write_default_env
        return 0
    fi

    upsert_env_value "$BASE_DIR/.env" "GML_VERSION" "$VERSION"
    upsert_env_value "$BASE_DIR/.env" "GML_PROXY_MODE" "$PROXY_MODE"
    upsert_env_value "$BASE_DIR/.env" "GML_PROXY_DOMAIN" "$PROXY_DOMAIN"
    upsert_env_value "$BASE_DIR/.env" "GML_PROXY_HTTPS_PORT" "$PROXY_HTTPS_PORT"
    upsert_env_value "$BASE_DIR/.env" "PORT_GML_FRONTEND" "$TARGET_FRONTEND_PORT"
}


# Docker Compose wrappers keep each operation as an isolated run_step target.
docker_compose_up() {
    cd "$BASE_DIR"
    docker compose up -d
}

docker_compose_up_with_pull() {
    cd "$BASE_DIR"
    docker compose up -d --pull always
}

docker_compose_down() {
    cd "$BASE_DIR"
    docker compose down
}

docker_compose_down_images() {
    cd "$BASE_DIR"
    docker compose down --rmi all
}

docker_compose_down_volumes() {
    cd "$BASE_DIR"
    docker compose down -v
}

validate_compose() {
    cd "$BASE_DIR"
    docker compose config >/dev/null
}

# The local connection validates both successful ACME issuance and the served
# certificate without depending on local DNS routing back through the internet.
wait_for_global_certificate() {
    [ "$PROXY_MODE" = "global" ] || return 0

    attempt=1
    while [ "$attempt" -le 60 ]; do
        if curl --noproxy '*' --silent --show-error --output /dev/null \
            --connect-timeout 3 --max-time 8 \
            --resolve "$PROXY_DOMAIN:443:127.0.0.1" \
            "https://$PROXY_DOMAIN/" 2>/dev/null; then
            return 0
        fi
        sleep 3
        attempt=$((attempt + 1))
    done

    echo "Timed out waiting for a valid Let’s Encrypt certificate for $PROXY_DOMAIN" >&2
    cd "$BASE_DIR"
    docker compose logs --tail 80 gml-web-proxy >&2 || true
    return 1
}

start_install_stack() {
    validate_compose || return 1
    docker_compose_up_with_pull || return 1

    if ! wait_for_global_certificate; then
        docker_compose_down || true
        return 1
    fi
}

# Update compose and installer-managed environment keys atomically. If the new
# proxy cannot start or obtain its certificate, restore the previous stack.
update_stack_transaction() {
    transaction_compose="$BASE_DIR/docker-compose.yml"
    transaction_env="$BASE_DIR/.env"
    transaction_staged_compose="$BASE_DIR/.docker-compose.yml.new.$$"
    transaction_staged_env="$BASE_DIR/.env.new.$$"
    transaction_backup_compose="$BASE_DIR/.docker-compose.yml.backup.$$"
    transaction_backup_env="$BASE_DIR/.env.backup.$$"

    [ -f "$transaction_compose" ] || {
        echo "Missing $transaction_compose" >&2
        return 1
    }
    [ -f "$transaction_env" ] || {
        echo "Missing $transaction_env" >&2
        return 1
    }

    curl -fsSL "$COMPOSE_URL" -o "$transaction_staged_compose" || return 1
    cp "$transaction_env" "$transaction_staged_env" || return 1
    upsert_env_value "$transaction_staged_env" "GML_VERSION" "$VERSION"
    upsert_env_value "$transaction_staged_env" "GML_PROXY_MODE" "$PROXY_MODE"
    upsert_env_value "$transaction_staged_env" "GML_PROXY_DOMAIN" "$PROXY_DOMAIN"
    upsert_env_value "$transaction_staged_env" "GML_PROXY_HTTPS_PORT" "$PROXY_HTTPS_PORT"
    upsert_env_value "$transaction_staged_env" "PORT_GML_FRONTEND" "$TARGET_FRONTEND_PORT"

    (
        cd "$BASE_DIR" &&
        docker compose --env-file "$transaction_staged_env" -f "$transaction_staged_compose" config >/dev/null
    ) || {
        rm -f "$transaction_staged_compose" "$transaction_staged_env"
        return 1
    }

    # Pull while the current stack is still serving traffic. The activation and
    # rollback paths can then start entirely from local images.
    (
        cd "$BASE_DIR" &&
        docker compose --env-file "$transaction_staged_env" -f "$transaction_staged_compose" pull
    ) || {
        rm -f "$transaction_staged_compose" "$transaction_staged_env"
        return 1
    }

    cp "$transaction_compose" "$transaction_backup_compose" || {
        rm -f "$transaction_staged_compose" "$transaction_staged_env"
        return 1
    }
    cp "$transaction_env" "$transaction_backup_env" || {
        rm -f "$transaction_staged_compose" "$transaction_staged_env" "$transaction_backup_compose"
        return 1
    }

    if ! docker_compose_down; then
        rm -f "$transaction_staged_compose" "$transaction_staged_env" "$transaction_backup_compose" "$transaction_backup_env"
        return 1
    fi

    mv "$transaction_staged_compose" "$transaction_compose"
    mv "$transaction_staged_env" "$transaction_env"

    if docker_compose_up && wait_for_global_certificate; then
        rm -f "$transaction_backup_compose" "$transaction_backup_env"
        return 0
    fi

    echo "New proxy mode failed; restoring the previous installation" >&2
    docker_compose_down || true
    mv "$transaction_backup_compose" "$transaction_compose"
    mv "$transaction_backup_env" "$transaction_env"

    if ! docker_compose_up; then
        echo "Rollback files were restored, but the previous stack could not be started" >&2
        return 1
    fi

    return 1
}


# Keep removed installations recoverable by moving the directory aside.
backup_install_directory() {
    timestamp=$(date +%Y%m%d_%H%M%S)
    parent_dir=$(dirname "$BASE_DIR")
    base_name=$(basename "$BASE_DIR")

    mv "$BASE_DIR" "$parent_dir/${base_name}_backup_$timestamp"
}

# Show reachable admin panel URLs after install or update.
write_success_message() {
    mode=$(get_env_value "$BASE_DIR/.env" "GML_PROXY_MODE")
    domain=$(get_env_value "$BASE_DIR/.env" "GML_PROXY_DOMAIN")
    port=$(get_env_value "$BASE_DIR/.env" "PORT_GML_FRONTEND")
    port=${port:-5003}
    ip_list=""

    if command -v ip >/dev/null 2>&1; then
        ip_list=$(ip -4 -o addr show up | awk '!/ lo / && !/docker|br-|veth/ {print $4}' | cut -d/ -f1 | sort -u)
    fi

    # Some containers expose `ip`, but it returns no matching addresses.
    if [ -z "$ip_list" ] && command -v hostname >/dev/null 2>&1; then
        ip_list=$(hostname -I 2>/dev/null)
    fi

    if [ -z "$ip_list" ] && [ -n "${SSH_CONNECTION:-}" ]; then
        ip_list=$(echo "$SSH_CONNECTION" | awk '{print $3}')
    fi

    # Always print at least an address that is reachable from the host itself.
    ip_list=${ip_list:-127.0.0.1}

    echo
    printf "\033[32m==================================================\033[0m\n"
    printf "\033[32m%s\033[0m\n" "$(message backend_ready)"
    printf "\033[32m==================================================\033[0m\n"
    message admin_panel
    printf "\n"

    if [ "$mode" = "global" ] && [ -n "$domain" ]; then
        echo " - https://$domain/"
        return 0
    fi

    for ip in $ip_list; do
        [ -n "$ip" ] && echo " - http://$ip:$port/"
    done
}

# Confirm that delete finished and the directory was backed up.
write_delete_message() {
    echo
    printf "\033[32m==================================================\033[0m\n"
    printf "\033[32m%s\033[0m\n" "$(message backend_removed)"
    printf "\033[32m==================================================\033[0m\n"
}

# Full installation flow. Every step must succeed before the next starts.
run_install() {
    run_step "$(message step_detect_os)" detect_os
    run_step "$(message step_prepare_os)" disable_additional_notify
    run_step "$(message step_install_curl)" ensure_command curl curl
    run_step "$(message step_install_openssl)" ensure_command openssl openssl
    run_step "$(message step_install_docker)" install_docker
    run_step "$(message step_install_network_tools)" ensure_socket_tools
    run_step "$(message step_check_empty_directory)" ensure_install_directory_empty
    run_step "$(message step_check_proxy)" check_proxy_requirements
    run_step "$(message step_create_directory)" prepare_directory
    run_step "$(message step_download_compose)" download_compose
    run_step "$(message step_update_env)" ensure_env
    run_step "$(message step_start_compose)" start_install_stack
    write_success_message
}

# Update the compose file, version variable, images, and running containers.
run_update() {
    run_step "$(message step_check_directory)" ensure_install_directory_exists
    if ! confirm_compose_overwrite; then
        return 0
    fi
    run_step "$(message step_install_curl)" ensure_command curl curl
    run_step "$(message step_install_network_tools)" ensure_socket_tools
    run_step "$(message step_check_proxy)" check_proxy_requirements
    run_step "$(message step_start_compose)" update_stack_transaction
    write_success_message
}

# Stop the stack, remove compose-managed resources, and back up the directory.
run_delete() {
    run_step "$(message step_check_directory)" ensure_install_directory_exists
    run_step "$(message step_stop_compose_volumes)" docker_compose_down_volumes
    run_step "$(message step_remove_images)" docker_compose_down_images
    run_step "$(message step_backup_directory)" backup_install_directory
    write_delete_message
}


# Entrypoint: parse, validate privileges, resolve prompts, then dispatch.
main() {
    detect_language "$@"
    print_banner
    parse_args "$@"
    resolve_language_input
    require_root
    resolve_action_and_base_dir
    resolve_proxy_inputs

    case "$ACTION" in
        install|update)
            if [ -z "$VERSION" ]; then
                run_step "$(message step_install_curl)" ensure_command curl curl
            fi
            ;;
    esac

    resolve_version_input

    case "$ACTION" in
        install)
            run_install
            ;;
        update)
            run_update
            ;;
        delete)
            run_delete
            ;;
        *)
            error "$(message unknown_action "$ACTION")"
            ;;
    esac
}

if [ "${GML_MANAGER_SKIP_MAIN:-0}" != "1" ]; then
    main "$@"
fi
